name: GitHub-Sync-Labels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - github_template/labels.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gh
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Install label-sync
        run: |
          npm install -g github-label-sync

      - name: Set GH_TOKEN
        run: echo "GH_TOKEN=${{ secrets.LABEL_SYNC_TOKEN  }}" >> $GITHUB_ENV

      - name: Sync
        run: |
          for repo in $(gh repo list ${{ github.repository_owner }} --limit 1000 --json nameWithOwner -q '.[].nameWithOwner'); do
            echo "Syncing $repo"
            github-label-sync "$repo" \
              --labels github_template/labels.yml \
              --access-token $GH_TOKEN
          done

      - name: Debug labels file
        run: cat github_template/labels.yml
