name: GitHub-Sync-Labels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - github_template/labels.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gh
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Login gh
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Install label-sync
        run: |
          npm install -g github-label-sync

      - name: Sync
        run: |
          for repo in $(gh repo list ${{ github.repository_owner }} --limit 1000 --json nameWithOwner -q '.[].nameWithOwner'); do
            github-label-sync "$repo" --labels github_template/labels.yml
          done
